[build]
builder = "nixpacks"
buildCommand = "cd backend && npm ci"

[deploy]
startCommand = "cd backend && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[[services]]
name = "clubos-backend"
port = 3001

[services.clubos-backend]
envVars = [
  "DATABASE_URL",
  "JWT_SECRET",
  "OPENAI_API_KEY",
  "ANTHROPIC_API_KEY",
  "SLACK_WEBHOOK_URL",
  "NODE_ENV=production",
  "PORT=3001"
]